[project]
name = "quic"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "jeff", email = "jeff@jeff3.win" }
]
dependencies = []
requires-python = ">= 3.8"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []
